sudo: true
git:
  submodules: false
branches:
  only:
  - master
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_c4d1162000ca_key -iv $encrypted_c4d1162000ca_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
install:
- npm install
script:
- npm km:build
after_success:
- ssh "$DEPLOY_USER"@"$DEPLOY_HOST" -o StrictHostKeyChecking=no 'cd /data/www/km &&
  git pull && bash ./deploy.sh'
addons:
  ssh_known_hosts:
  - $DEPLOY_HOST
